# Generated by Django 4.2.4 on 2023-09-05 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reactPortfolioBackend', '0002_alter_landingpagedata_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='landingpagedata',
            name='picture',
            field=models.ImageField(upload_to='static'),
        ),
    ]
